[project]
name = "studd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy==1.23.5",
    "pandas>=2.0.3",
    "scikit-multiflow>=0.5.3",
]
